# Default values for zenix (prod)
# Les images sont mises à jour par la CI (workflow build-and-push)

namespace: zenix
nameOverride: ""
fullnameOverride: ""

imagePullSecrets:
  - name: ghcr-secret

# Backend (Node)
backend:
  image: ghcr.io/emmguardia/zenix-backend@sha256:8d11d5c2c599633d61b058413d0c29a07c6dc66c51b3887e869f74235ea6ff8d
  imagePullPolicy: IfNotPresent
  replicas: 1
  port: 3000
  env:
    PORT: "3000"
    NODE_ENV: production
    JWT_PRIVATE_KEY_PATH: /app/secrets/jwt_private_key.pem
    EMAIL_SERVICE_URL: http://email-service.email-service.svc.cluster.local:8080
    ALLOWED_ORIGINS: "https://www.zenixweb.fr,http://localhost:5173"
  secretName: zenix-backend-secrets
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  hpa:
    minReplicas: 1
    maxReplicas: 4
    cpuTarget: 70
    memoryTarget: 80

# Frontend (nginx)
frontend:
  image: ghcr.io/emmguardia/zenix-front@sha256:d6cb6c05c839e0ea2d7f99b7b7955263f9371f6daf195a053d85f58637c7b0e3
  imagePullPolicy: Always
  replicas: 1
  serviceType: NodePort
  port: 80
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "300m"
      memory: "256Mi"
  hpa:
    minReplicas: 1
    maxReplicas: 4
    cpuTarget: 70
    memoryTarget: 80
