# Default values for zenix (prod)
# Les images sont mises à jour par la CI (workflow build-and-push)

namespace: zenix
nameOverride: ""
fullnameOverride: ""

imagePullSecrets:
  - name: ghcr-secret

# Backend (Node)
backend:
  image: ghcr.io/emmguardia/zenix-backend@sha256:6f6f8bdf475b570d5ada8ecfd99b07267d36bfb23eaa7e8f5f38aa04c3140e69
  imagePullPolicy: IfNotPresent
  replicas: 1
  port: 3000
  env:
    PORT: "3000"
    NODE_ENV: production
    JWT_PRIVATE_KEY_PATH: /app/secrets/jwt_private_key.pem
    EMAIL_SERVICE_URL: http://email-service.email-service.svc.cluster.local:8080
    ALLOWED_ORIGINS: "https://www.zenixweb.fr,http://localhost:5173"
  secretName: zenix-backend-secrets
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  hpa:
    minReplicas: 1
    maxReplicas: 4
    cpuTarget: 70
    memoryTarget: 80

# Frontend (nginx)
frontend:
  image: ghcr.io/emmguardia/zenix-front@sha256:98094b232fc9df2c0020679c168b42581896ff81983a8deeee299544df222542
  imagePullPolicy: Always
  replicas: 1
  serviceType: NodePort
  port: 80
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "300m"
      memory: "256Mi"
  hpa:
    minReplicas: 1
    maxReplicas: 4
    cpuTarget: 70
    memoryTarget: 80
